/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BoxId = string;
export interface BoxSummary {
  'id' : BoxId,
  'name' : string,
  'pdfCount' : bigint,
}
export type PdfId = string;
export interface PdfMeta {
  'id' : PdfId,
  'title' : string,
  'downloadUrl' : string,
  'fileSize' : string,
  'boxId' : BoxId,
  'roomId' : RoomId,
  'chapterName' : string,
}
export type RoomId = string;
export interface RoomSummary {
  'id' : RoomId,
  'name' : string,
  'boxCount' : bigint,
  'pdfCount' : bigint,
}
export interface _SERVICE {
  'addBookmark' : ActorMethod<[PdfId], boolean>,
  'getAllRooms' : ActorMethod<[], Array<RoomSummary>>,
  'getBookmarks' : ActorMethod<[], Array<PdfMeta>>,
  'getBoxesByRoom' : ActorMethod<[RoomId], Array<BoxSummary>>,
  'getPdfsByBox' : ActorMethod<[RoomId, BoxId], Array<PdfMeta>>,
  'getPdfsByRoom' : ActorMethod<[RoomId], Array<PdfMeta>>,
  'getRecentlyViewed' : ActorMethod<[], Array<PdfMeta>>,
  'markViewed' : ActorMethod<[PdfId], undefined>,
  'removeBookmark' : ActorMethod<[PdfId], boolean>,
  'searchPdfs' : ActorMethod<[string], Array<PdfMeta>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];