/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PdfId = IDL.Text;
export const RoomId = IDL.Text;
export const RoomSummary = IDL.Record({
  'id' : RoomId,
  'name' : IDL.Text,
  'boxCount' : IDL.Nat,
  'pdfCount' : IDL.Nat,
});
export const BoxId = IDL.Text;
export const PdfMeta = IDL.Record({
  'id' : PdfId,
  'title' : IDL.Text,
  'downloadUrl' : IDL.Text,
  'fileSize' : IDL.Text,
  'boxId' : BoxId,
  'roomId' : RoomId,
  'chapterName' : IDL.Text,
});
export const BoxSummary = IDL.Record({
  'id' : BoxId,
  'name' : IDL.Text,
  'pdfCount' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addBookmark' : IDL.Func([PdfId], [IDL.Bool], []),
  'getAllRooms' : IDL.Func([], [IDL.Vec(RoomSummary)], ['query']),
  'getBookmarks' : IDL.Func([], [IDL.Vec(PdfMeta)], ['query']),
  'getBoxesByRoom' : IDL.Func([RoomId], [IDL.Vec(BoxSummary)], ['query']),
  'getPdfsByBox' : IDL.Func([RoomId, BoxId], [IDL.Vec(PdfMeta)], ['query']),
  'getPdfsByRoom' : IDL.Func([RoomId], [IDL.Vec(PdfMeta)], ['query']),
  'getRecentlyViewed' : IDL.Func([], [IDL.Vec(PdfMeta)], ['query']),
  'markViewed' : IDL.Func([PdfId], [], []),
  'removeBookmark' : IDL.Func([PdfId], [IDL.Bool], []),
  'searchPdfs' : IDL.Func([IDL.Text], [IDL.Vec(PdfMeta)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PdfId = IDL.Text;
  const RoomId = IDL.Text;
  const RoomSummary = IDL.Record({
    'id' : RoomId,
    'name' : IDL.Text,
    'boxCount' : IDL.Nat,
    'pdfCount' : IDL.Nat,
  });
  const BoxId = IDL.Text;
  const PdfMeta = IDL.Record({
    'id' : PdfId,
    'title' : IDL.Text,
    'downloadUrl' : IDL.Text,
    'fileSize' : IDL.Text,
    'boxId' : BoxId,
    'roomId' : RoomId,
    'chapterName' : IDL.Text,
  });
  const BoxSummary = IDL.Record({
    'id' : BoxId,
    'name' : IDL.Text,
    'pdfCount' : IDL.Nat,
  });
  
  return IDL.Service({
    'addBookmark' : IDL.Func([PdfId], [IDL.Bool], []),
    'getAllRooms' : IDL.Func([], [IDL.Vec(RoomSummary)], ['query']),
    'getBookmarks' : IDL.Func([], [IDL.Vec(PdfMeta)], ['query']),
    'getBoxesByRoom' : IDL.Func([RoomId], [IDL.Vec(BoxSummary)], ['query']),
    'getPdfsByBox' : IDL.Func([RoomId, BoxId], [IDL.Vec(PdfMeta)], ['query']),
    'getPdfsByRoom' : IDL.Func([RoomId], [IDL.Vec(PdfMeta)], ['query']),
    'getRecentlyViewed' : IDL.Func([], [IDL.Vec(PdfMeta)], ['query']),
    'markViewed' : IDL.Func([PdfId], [], []),
    'removeBookmark' : IDL.Func([PdfId], [IDL.Bool], []),
    'searchPdfs' : IDL.Func([IDL.Text], [IDL.Vec(PdfMeta)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };