/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface BoxSummary {
    id: BoxId;
    name: string;
    pdfCount: bigint;
}
export interface RoomSummary {
    id: RoomId;
    name: string;
    boxCount: bigint;
    pdfCount: bigint;
}
export type RoomId = string;
export type BoxId = string;
export interface PdfMeta {
    id: PdfId;
    title: string;
    downloadUrl: string;
    fileSize: string;
    boxId: BoxId;
    roomId: RoomId;
    chapterName: string;
}
export type PdfId = string;
export interface backendInterface {
    addBookmark(pdfId: PdfId): Promise<boolean>;
    getAllRooms(): Promise<Array<RoomSummary>>;
    getBookmarks(): Promise<Array<PdfMeta>>;
    getBoxesByRoom(roomId: RoomId): Promise<Array<BoxSummary>>;
    getPdfsByBox(roomId: RoomId, boxId: BoxId): Promise<Array<PdfMeta>>;
    getPdfsByRoom(roomId: RoomId): Promise<Array<PdfMeta>>;
    getRecentlyViewed(): Promise<Array<PdfMeta>>;
    markViewed(pdfId: PdfId): Promise<void>;
    removeBookmark(pdfId: PdfId): Promise<boolean>;
    searchPdfs(searchQuery: string): Promise<Array<PdfMeta>>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addBookmark(arg0: PdfId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addBookmark(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBookmark(arg0);
            return result;
        }
    }
    async getAllRooms(): Promise<Array<RoomSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRooms();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRooms();
            return result;
        }
    }
    async getBookmarks(): Promise<Array<PdfMeta>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookmarks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookmarks();
            return result;
        }
    }
    async getBoxesByRoom(arg0: RoomId): Promise<Array<BoxSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBoxesByRoom(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBoxesByRoom(arg0);
            return result;
        }
    }
    async getPdfsByBox(arg0: RoomId, arg1: BoxId): Promise<Array<PdfMeta>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPdfsByBox(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPdfsByBox(arg0, arg1);
            return result;
        }
    }
    async getPdfsByRoom(arg0: RoomId): Promise<Array<PdfMeta>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPdfsByRoom(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPdfsByRoom(arg0);
            return result;
        }
    }
    async getRecentlyViewed(): Promise<Array<PdfMeta>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecentlyViewed();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecentlyViewed();
            return result;
        }
    }
    async markViewed(arg0: PdfId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markViewed(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markViewed(arg0);
            return result;
        }
    }
    async removeBookmark(arg0: PdfId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeBookmark(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeBookmark(arg0);
            return result;
        }
    }
    async searchPdfs(arg0: string): Promise<Array<PdfMeta>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchPdfs(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchPdfs(arg0);
            return result;
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
